### ISSUE TITLE
1er onglet : plantage de la requête AJAX de recherche LDAP.

### ISSUE THREAD

**Issue by ppomedio** [Unice-SIL/syllabus#2]
Suivant ce que l'on saisit dans le champ de recherche ("du", "el"…) la requête AJAX proposant une liste de personnes plante (500).

<img width="762" alt="Capture d’écran 2019-04-17 à 11 39 02" src="https://user-images.githubusercontent.com/10742818/56278034-c4714880-6105-11e9-8a42-b65e7a628487.png">

**Comment by ppomedio** [comment]
<img width="1000" alt="Capture d’écran 2019-04-17 à 11 53 35" src="https://user-images.githubusercontent.com/10742818/56278951-7bba8f00-6107-11e9-8dcd-b404ef56daf8.png">

**Comment by FredericCasazza** [comment]
Corrigé !
Pour certains résultats de requête LDAP l'attribut nom ou prénom pouvait être vide hors les getters de ces mêmes attributs de la classe Teacher devaient obligatoirement retourner un string. Maintenant null est aussi autorisé.
